# Generated by Django 5.1.4 on 2026-08-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('statuts', 'Statuts'), ('m0', 'Formulaire M0'), ('dnc', 'Declaration de non-condamnation'), ('beneficiaires', 'Registre des beneficiaires effectifs')], max_length=16)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Valide'), ('signe', 'Signe')], default='brouillon', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(editable=False, max_length=6)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('signe', 'Signe'), ('expire', 'Expire')], default='en_attente', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='documents.legaldocument')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
