# Generated by Django 5.1.4 on 2026-08-28 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='raison sociale')),
                ('legal_form', models.CharField(choices=[('SAS', 'SAS'), ('SASU', 'SASU'), ('SARL', 'SARL'), ('EURL', 'EURL'), ('SCI', 'SCI'), ('MICRO', 'Micro-entreprise')], max_length=8)),
                ('share_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_revue', 'En revue'), ('depose', 'Depose au greffe'), ('immatricule', 'Immatricule')], default='brouillon', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ('-created_at',),
            },
        ),
    ]
